# This is a basic workflow to help you get started with Actions

name: Pre Merge Check

# Controls when the action will run. 
on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Set up projects
        run: |
          dotnet new classlib -o Runtime -n Runtime
          rm Runtime/Class1.cs
          
          dotnet new nunit -o Test -n Test
          rm Test/UnitTest1.cs
          rm Test/Usings.cs

          dotnet add Test/Test.csproj reference Runtime/Runtime.csproj

      - name: Test with dotnet
        run: dotnet test Test --logger trx --results-directory "TestResults"
      
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-results
          path: TestResults
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}

      - name: Clean up
        run: rm -rf TestResults

